### ISSUE TITLE
Modrinth Request

### ISSUE THREAD

**Issue by TskimiSeiran** [Theyoungster/Quicksand-Rehydrated#1]
https://modrinth.com
Hello,Author,I like your mod but some player hardly to download and build at github,This site named "modrinth",you can put your mod on this site.

**Comment by Theyoungster** [comment]
Thank you for the interest! This is an extremely early development build, and simply isn't ready for even the earliest of beta releases.

Rest assured, when we have a mod to present to the public, it will be available on Modrinth and Curseforge, and on the repo's Releases page.

In the meantime, you will get more active updates on [our Discord](https://discord.com/invite/RmpR94fXTb). We'd love to see you there!
