### ISSUE TITLE
[main/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/KeyMapping for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by waterdragon78** [Theyoungster/Quicksand-Rehydrated#11]
### Issue:
So my friend wanted this mod in a server that I'm running for him, so I compiled it and attempted to put it in. For some reason, it crashes before even getting to the point that a crash log could be made. I will send the debug and latest log here. The mod does work on single player, though.
### Information:
- Mod version from commit: https://github.com/Theyoungster/Quicksand-Rehydrated/commit/7d1c5d2b82c5f8e3ad4466727a3ca6d8065c6f21
- Branch: Quicksandbehavior_test
- OS: macOS 15.1
- Arch: aarch/arm64
- Java: 17.0.2 Azul
- Built with: ./gradlew build (Unsure if this is relevant or not)
I will add any other relevant info upon request, this is just all I could think of off the top of my head.
### Logs:
- [debug.log](https://github.com/user-attachments/files/18172197/debug.log)
- [latest.log](https://github.com/user-attachments/files/18172198/latest.log)

**Comment by Theyoungster** [comment]
Unfortunately, it' going to be a while before we have a multiplayer-viable build is available; we're still VERY early in development. Sorry!
